name: Compiler

on: [push]

jobs:
  build_osx:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.5
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.5.x
    - name: Install dependencies
      run: brew install squashfs
    - name: Lookup
      run: ls
    - name: run build
      run: make build
