name: Compiler

on: [push]

jobs:
  build_osx:
    runs-on: macOS-10.14
    steps:
    - uses: actions/checkout@v1
    - name: install perlbrew
      run: curl -L https://install.perlbrew.pl | bash &&  source ~/perl5/perlbrew/etc/bashrc
    - name: Install perl 5.16.0
      run: perlbrew install perl-5.16.0
    - name: Switch perl
      run: perlbrew switch perl-5.16.0
    - name: Perl version
      run: perl -v
    - name: Install dependencies
      run: brew install squashfs
    - name: run build
      run: make build
