name: compile

on: [push,pull_request]

jobs:
  build_osx:
    runs-on: macOS-10.14
    env:
      PERL_LWP_SSL_VERIFY_HOSTNAME: 0
    steps:
    - uses: actions/checkout@v1
    - uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: '5.16.2'
    # - name: install plenv
    #   run: brew update && brew install plenv
    #   # && brew install perl-build
    # - name: Activate plenv
    #   run: eval "$(plenv init -)"
    # - name: Install Perl-Build as plenv plugin
    #   run: git clone git://github.com/tokuhirom/Perl-Build.git $(plenv root)/plugins/perl-build/
    # - name: Install perl 5.16.2
    #   run: plenv install 5.16.2 -Dusethreads
    # - name: Reactivate plenv
    #   run: eval "$(plenv init -)"
    # - name: set global perl
    #   run: plenv global 5.16.2 && plenv local 5.16.2
    # - name: plenv rehash
    #   run: plenv rehash
    - name: Perl version
      run: perl -v
    # - name: Install dependencies
    #   run: brew install squashfs
    # - name: run build
    #   run: make build
