name: compile

on: [push,pull_request]

jobs:
  build_osx:
    runs-on: macOS-10.14
    env:
      PERL_LWP_SSL_VERIFY_HOSTNAME: 0
    steps:
    - uses: actions/checkout@v1
    - uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: '5.16.2'
    - name: Perl version
      run: perl -v
    - name: Install dependencies
      run: brew install squashfs
    - name: run build
      run: make build
