name: macos

on:
  push:
    branches: [ master ]
    tags: [ '*' ]
  pull_request:
    paths-ignore:
      - .github/workflows/linux.yml
      - .github/workflows/windows.yml
      - .github/workflows/release_tag.yml
      - Makefile.win

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'

      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.16.2'

      - run: |
          curl -Lks 'https://git.io/rg-ssl' | ruby
          echo "perl -v: $(perl -v)"
          echo "clang -v: $(clang -v)"
          echo "clang++ -v: $(clang -v)"

      - run: brew install squashfs

      - run: make build
        env:
          DEVELOPER_DIR: /Applications/Xcode_11.7.app/Contents/Developer

      - uses: actions/upload-artifact@v2
        with:
          name: metanorma-macos
          path: build/metanorma

  test:
    runs-on: macos-latest
    needs: build
    steps:
      - uses: actions/checkout@v1

      - uses: actions/download-artifact@v2
        with:
          name: metanorma-macos
          path: build

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'

      - run: chmod a+x build/metanorma

      - run: make test test-site-gen
        env:
          GITHUB_CREDENTIALS: "metanorma-ci:${{ secrets.METANORMA_CI_PAT_TOKEN }}"

      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: samples_macos_logs
          path: test_*.log

      - uses: actions/upload-artifact@v2
        with:
          name: samples
          path: build/**/published/*

  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: macos-latest
    needs: test
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: metanorma-macos
          path: build

      - name: Set release binary permissions
        run: |
          cp build/metanorma metanorma-darwin-x64
          chmod a+x metanorma-darwin-x64
          tar -czvf metanorma-darwin-x64.tgz metanorma-darwin-x64

      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: metanorma-darwin-x64.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.METANORMA_CI_PAT_TOKEN }}
          repository: metanorma/homebrew-metanorma
          event-type: ${{ github.repository }}
          client-payload: '{ "ref": "${{ github.ref }}" }'