name: test_no_build

on:
  pull_request:
    paths-ignore:
      - .github/workflows/linux.yml
      - .github/workflows/macos.yml
      - .github/workflows/windows.yml
      - .github/workflows/release_tag.yml
      - Makefile.win

jobs:
  test_no_build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - 2.3.8
          - 2.4.1
          - 2.4.2
          - 2.4.3
          - 2.4.4
          - 2.4.5
          - 2.4.6
          - 2.4.7
          - 2.4.8
          - 2.4.9
          - 2.4.10
          - 2.5.0
    steps:
    - uses: actions/checkout@v2

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler: 2.2.3
        bundler-cache: true

    - run: bundle update --all

    - name: Setup working dir
      run: |
        cp bin/metanorma .
        chmod +x metanorma
        git clone --recurse-submodules https://github.com/metanorma/mn-samples-iso build/iso

    - run: ./metanorma site generate build/iso -c build/iso/metanorma.yml -o build/site/iso --agree-to-terms
