name: windows

on:
  push:
    branches: [ master ]
    tags: [ '*' ]
  pull_request:
    paths-ignore:
      - .github/workflows/linux.yml
      - .github/workflows/macos.yml
      - .github/workflows/release_tag.yml
      - Makefile
      - bin/build.sh

jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v1

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.4'

    - run: gem -v

    - run: systeminfo

    - uses: nick-invision/retry@v1
      with:
        polling_interval_seconds: 5
        timeout_minutes: 5
        max_attempts: 3
        command: choco install --no-progress make gnuwin32-coreutils.install gzip wget git

    - run: bundle install

    - run: "%ChocolateyInstall%\\bin\\make -f Makefile.win build build/metanorma.exe SHELL=cmd"
      shell: cmd

    - run: .\\build\\metanorma.exe help

    - uses: actions/upload-artifact@v2
      with:
        name: metanorma-windows
        path: build/metanorma.exe

  test:
    runs-on: windows-2019
    needs: build
    steps:
      - uses: actions/checkout@v1

      - uses: actions/download-artifact@v2
        with:
          name: metanorma-windows
          path: build

      - run: .\build\metanorma.exe help

      - uses: nick-invision/retry@v1
        with:
          polling_interval_seconds: 5
          timeout_minutes: 5
          max_attempts: 3
          command: choco install --no-progress yq make gnuwin32-coreutils.install gzip wget unzip git

      - uses: nick-invision/retry@v1
        with:
          polling_interval_seconds: 5
          timeout_minutes: 5
          max_attempts: 3
          command: choco install --no-progress yq --version 3.4.1 --allow-downgrade

      - run: |
          & gem install relaton-cli
          & ${env:ChocolateyInstall}\bin\make.exe -f Makefile.win test-flavor SHELL=cmd TEST_FLAVOR=cc
          & ${env:ChocolateyInstall}\bin\make.exe -f Makefile.win test-flavor SHELL=cmd TEST_FLAVOR=iso
          & ${env:ChocolateyInstall}\bin\make.exe -f Makefile.win test-flavor SHELL=cmd TEST_FLAVOR=gb
          & ${env:ChocolateyInstall}\bin\make.exe -f Makefile.win test-flavor SHELL=cmd TEST_FLAVOR=iec
          & ${env:ChocolateyInstall}\bin\make.exe -f Makefile.win test-flavor SHELL=cmd TEST_FLAVOR=un
          & ${env:ChocolateyInstall}\bin\make.exe -f Makefile.win test-flavor SHELL=cmd TEST_FLAVOR=iho
          & ${env:ChocolateyInstall}\bin\make.exe -f Makefile.win test-flavor SHELL=cmd TEST_FLAVOR=nist
        env:
          GITHUB_CREDENTIALS: "metanorma-ci:${{ secrets.METANORMA_CI_PAT_TOKEN }}"
          SKIP_BUNDLE: true

      - if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: samples_windows_logs
          path: test_*.log

  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: windows-latest
    needs: test
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: metanorma-windows
          path: build

      - run: cp build/metanorma.exe metanorma-windows-x64.exe

      - if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: softprops/action-gh-release@v1
        with:
          files: metanorma-windows-x64.exe

      - name: Trigger chocolatey-metanorma
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.METANORMA_CI_PAT_TOKEN }}
          repository: metanorma/chocolatey-metanorma
          event-type: ${{ github.repository }}
          client-payload: '{ "ref": "${{ github.ref }}" }'
